---
name: cmpsc-100-fall-2018-practical9
break: true
indent: 4
---
src/main:
    java:
        practicalnine/DisplaySymbols.java:
            --single 5 --language Java
            --multi 3 --language Java
            --fragment "new Date(" --count 1
            --fragment "println(" --count 10
            --fragment "displaySymbolInTriangle" --count 2
            --fragment "displaySymbolInDoubleTriangle" --count 2
            --fragment "while" --count 2
--commits 2

--command "gradle -q --console plain run" --executes
